package com.corejava.Exception;

public class StackTrace1 {
	
	public static void main(String[] args) {
		
		try {
			System.out.println("Inside try blck");
	}
		catch(RuntimeException e) {
			
		}

}
}
